export const TRACK_NAMES: Record<number, string> = {
  0: 'Melbourne',
  1: 'Paul Ricard',
  2: 'Shanghai',
  3: 'Bahrain',
  4: 'Catalunya',
  5: 'Monaco',
  6: 'Montreal',
  7: 'Silverstone',
  8: 'Hockenheim',
  9: 'Hungaroring',
  10: 'Spa',
  11: 'Monza',
  12: 'Singapore',
  13: 'Suzuka',
  14: 'Abu Dhabi',
  15: 'COTA',
  16: 'Brazil',
  17: 'Austria',
  18: 'Sochi',
  19: 'Mexico City',
  20: 'Baku',
  21: 'Bahrain Short',
  22: 'Silverstone Short',
  23: 'COTA Short',
  24: 'Suzuka Short',
  25: 'Hanoi',
  26: 'Zandvoort',
  27: 'Imola',
  28: 'Portimao',
  29: 'Jeddah',
  30: 'Miami',
  31: 'Las Vegas',
  32: 'Lusail',
}

export const SESSION_TYPES: Record<number, string> = {
  0: 'Unknown',
  1: 'Practice 1',
  2: 'Practice 2',
  3: 'Practice 3',
  4: 'Practice (Short)',
  5: 'Q1',
  6: 'Q2',
  7: 'Q3',
  8: 'Qualifying (Short)',
  9: 'One-Shot Q',
  10: 'Race',
  11: 'Race 2',
  12: 'Race 3',
  13: 'Time Trial',
}

export const TYRE_COMPOUNDS: Record<number, { name: string; color: string }> = {
  7:  { name: 'Intermediate', color: '#39b54a' },
  8:  { name: 'Wet',          color: '#0067ff' },
  16: { name: 'Soft',         color: '#e8002d' },
  17: { name: 'Medium',       color: '#ffd700' },
  18: { name: 'Hard',         color: '#e5e7eb' },
}

export const TEAM_NAMES: Record<number, string> = {
  0:   'Mercedes',
  1:   'Ferrari',
  2:   'Red Bull',
  3:   'Williams',
  4:   'Aston Martin',
  5:   'Alpine',
  6:   'RB',
  7:   'Haas',
  8:   'McLaren',
  9:   'Sauber',
  41:  'F2 Generic',
  85:  'My Team',
  255: 'Unknown',
}

export const WEATHER: Record<number, string> = {
  0: 'Clear',
  1: 'Light Cloud',
  2: 'Overcast',
  3: 'Light Rain',
  4: 'Heavy Rain',
  5: 'Storm',
}

export const SESSION_TYPE_COLORS: Record<string, string> = {
  'Race':               'bg-red-900/60 text-red-300',
  'Race 2':             'bg-red-900/60 text-red-300',
  'Race 3':             'bg-red-900/60 text-red-300',
  'Q1':                 'bg-purple-900/60 text-purple-300',
  'Q2':                 'bg-purple-900/60 text-purple-300',
  'Q3':                 'bg-purple-900/60 text-purple-300',
  'One-Shot Q':         'bg-purple-900/60 text-purple-300',
  'Qualifying (Short)': 'bg-purple-900/60 text-purple-300',
  'Practice 1':         'bg-blue-900/60 text-blue-300',
  'Practice 2':         'bg-blue-900/60 text-blue-300',
  'Practice 3':         'bg-blue-900/60 text-blue-300',
  'Practice (Short)':   'bg-blue-900/60 text-blue-300',
  'Time Trial':         'bg-yellow-900/60 text-yellow-300',
}
